Update Is Subsequence.py
New concepts learned:

-->Split method:
Split method takes in two arguments. One is a regular expression, the other the string. I tried using this method and learnt about its arguments through this error code: 
TypeError: split() missing 1 required positional argument: 'string'

--> Use of pointer:
Used a pointer to act as a counter for the times an occurrence of same letter happens in string T as compared to string S.